# Auto-generated with compile.py at 2024-07-04 20:21:20.778457+00:00

# src/raw_commands/DOWNLOAD_FILE.py
DOWNLOAD_FILE = lambda pico_filename : f"exec('try:\\n    import sys\\n    pico_filename = \\\"{pico_filename}\\\"\\n    with open(pico_filename, \\\'r\\\') as f:\\n        print(f.read(), end=\\\'\\\')\\n\\nexcept Exception as e:\\n    sys.print_exception(e)\\n    print(f\\\"FAILED---0dfe99a5-4543-4fc0-8986-5d7fd5e51d7b---ERROR\\\")')"

# src/raw_commands/CREATE_DIR.py
CREATE_DIR = lambda overwrite, directory : f"exec('try:\\n    import sys\\n    import os\\n    overwrite = \\\"{overwrite}\\\"\\n    directory = \\\"{directory}\\\"\\n    overwrite = True if overwrite == \\\"True\\\" else False\\n    S_IFDIR = 0o040000  \\n    def S_IFMT(mode): \\n        return mode & 0o170000\\n    def S_ISDIR(mode): \\n        return S_IFMT(mode) == S_IFDIR\\n    def delete_dir(path):\\n        items = os.listdir(path)  \\n        for item in items:\\n            full_path = \\\'/\\\'.join([path, item]) \\n            if S_ISDIR(os.stat(full_path)[0]):  \\n                delete_dir(full_path)  \\n                os.rmdir(full_path)  \\n            else:\\n                os.remove(full_path)  \\n        os.rmdir(path)  \\n    if overwrite:\\n        delete_dir(directory)\\n    try:\\n        if S_ISDIR(os.stat(directory)[0]):\\n            raise ValueError(f\\\"Directory {{directory}} already exists! Set \\\'--overwrite\\\' to delete it and create a new one.\\\")\\n    except OSError:\\n        pass\\n    os.mkdir(directory)\\n\\nexcept Exception as e:\\n    sys.print_exception(e)\\n    print(f\\\"FAILED---0dfe99a5-4543-4fc0-8986-5d7fd5e51d7b---ERROR\\\")')"

# src/raw_commands/DELETE_ITEM.py
DELETE_ITEM = lambda is_recursive, item_path : f"exec('try:\\n    import sys\\n    import os\\n    recursive = \\\"{is_recursive}\\\"\\n    item_path = \\\"{item_path}\\\"\\n    recursive = True if recursive == \\\"True\\\" else False\\n    S_IFDIR = 0o040000  \\n    def S_IFMT(mode): \\n        return mode & 0o170000\\n    def S_ISDIR(mode): \\n        return S_IFMT(mode) == S_IFDIR\\n    def delete_files_and_dirs(path, recursive=True):\\n        \\\"\\\"\\\"Delete files and directories at a given path.\\\"\\\"\\\"\\n        if recursive and S_ISDIR(os.stat(path)[0]):\\n            \\n            items = os.listdir(path)\\n            \\n            for item in items:\\n                full_path = \\\'/\\\'.join([path, item])\\n                delete_files_and_dirs(full_path, recursive)\\n            \\n            \\n            os.rmdir(path)\\n        else:\\n            \\n            os.remove(path)\\n    delete_files_and_dirs(item_path, recursive)\\n\\nexcept Exception as e:\\n    sys.print_exception(e)\\n    print(f\\\"FAILED---0dfe99a5-4543-4fc0-8986-5d7fd5e51d7b---ERROR\\\")')"

# src/raw_commands/UPLOAD_FILE.py
UPLOAD_FILE = lambda hex_data, pico_file_path, overwrite : f"exec('try:\\n    import sys\\n    import os\\n    hex_data = \\\"{hex_data}\\\"\\n    pico_file_path = \\\"{pico_file_path}\\\"\\n    overwrite = \\\"{overwrite}\\\"\\n    overwrite = True if overwrite == \\\"True\\\" else False\\n    S_IFDIR = 0o040000  \\n    def S_IFMT(mode): \\n        return mode & 0o170000\\n    def S_ISDIR(mode): \\n        return S_IFMT(mode) == S_IFDIR\\n    try:\\n        \\n        file_stat = os.stat(pico_file_path)[0]\\n        \\n        if S_ISDIR(file_stat):\\n            raise ValueError(f\\\"{{pico_file_path}} is a directory. Aborting upload.\\\")\\n        \\n        if overwrite:\\n            os.remove(pico_file_path)\\n        else:\\n            raise ValueError(f\\\"File {{pico_file_path}} already exists! Set \\\'--overwrite\\\' to delete it and create a new one.\\\")\\n    except OSError:\\n        pass \\n    decoded_data = bytes.fromhex(hex_data)\\n    with open(pico_file_path, \\\"wb\\\") as f: \\n        f.write(decoded_data)\\n    print(\\\"File uploaded successfully!\\\")\\n\\nexcept Exception as e:\\n    sys.print_exception(e)\\n    print(f\\\"FAILED---0dfe99a5-4543-4fc0-8986-5d7fd5e51d7b---ERROR\\\")')"

# src/raw_commands/LS_DIR.py
LS_DIR = lambda directory : f"exec('try:\\n    import sys\\n    import os\\n    path = \\\"{directory}\\\"\\n    S_IFDIR = 0o040000  \\n    def S_IFMT(mode): \\n        return mode & 0o170000\\n    def S_ISDIR(mode): \\n        return S_IFMT(mode) == S_IFDIR\\n    try:\\n        os.stat(path)\\n    except OSError:\\n        raise OSError(f\\\"{{path}} does not exist!\\\")\\n    if not S_ISDIR(os.stat(path)[0]):  \\n        raise OSError(f\\\"{{path}} is not a directory!\\\")\\n    print(os.listdir(path))\\n\\nexcept Exception as e:\\n    sys.print_exception(e)\\n    print(f\\\"FAILED---0dfe99a5-4543-4fc0-8986-5d7fd5e51d7b---ERROR\\\")')"